# Site settings
title: Kim Young Jun
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kim Young Jun<br>
user_description: 통계학을 전공했고, 관련 공부와 업무를 이어왔습니다.<br>여러 툴이나 언어(SAS, SPSS, R, C++, ASP, PHP, Node.js, Java, CodeIgniter)를 사용할 수 있습니다.<br>Spring Boot, JPA, MySql기반으로 제작한 다면평가, 실적평가 시스템 그리고, 이를 운영할 수 있는 지식과 경험을 가지고 있습니다.<br><br> <p>1. 다면평가 시스템을 소개해 드립니다.<a href="http://companysurvey.shop/surveys/demo" target="_blank">연결</a><h4>( id - kimyj@demo.com / pw - 1234 )</h4></p><br><p>2. 실적평가 시스템을 소개해 드립니다.<a href="http://companysurvey.shop/mbos/demo" target="_blank">연결</a><h4>( id - kimyj@demo.com / pw - 1234 )</h4></p><br><p>3. 관리자 시스템을 소개해 드립니다.<a href="http://companysurvey.shop" target="_blank">연결<a/><h4>( id - demo / pw - 1234 )</h4></p><h2><a aria-label="My Github" target="_blank" href="https://github.com/yorez/evaluationJpa"><i class="icon fa fa-github-alt" aria-hidden="true"></i>CODE</a></h2>
user_title: statistics & data collection
email: yorez@naver.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
